apiVersion: v1
kind: Service
metadata:
  name: igrant-user-docs-svc
  namespace: production
  labels:
    app: igrant-user-docs
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: igrant-user-docs
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: igrant-user-docs
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: igrant-user-docs
    spec:
      containers:
        - name: igrant-user-docs
          image: eu.gcr.io/jenkins-189019/igrant-user-docs:HEAD-20201007140813-
          ports:
            - containerPort: 80

---

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: igrant-user-docs-ing
  namespace: production
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
        - docs.igrant.io
      secretName: tls-secret

  rules:
    - host: docs.igrant.io
      http:
        paths:
          - path: /
            backend:
              serviceName: igrant-user-docs-svc
              servicePort: 80
          - path: /*
            backend:
              serviceName: igrant-user-docs-svc
              servicePort: 80

# Change the frontend ing with the path /admin point to igrant-privacy-svc
